UPDATE `addresses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `announcements` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `announcement_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `assessments` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `assessment_categories` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `assessment_category_category_question` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `assessment_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `assets` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `asset_conditions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `asset_groups` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `asset_suppliers` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `branches` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `category_questions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `category_question_choices` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `category_question_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `commentdetails` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `companies` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `countries` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `courseparticipantstatuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `courses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `days` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `departments` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `disciplinary_actions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `disciplinary_decisions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `divisions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `document_categories` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `document_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `email_addresses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `employees` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `employee_attachments` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `employee_attachment_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `employee_evaluation` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `employee_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `employee_training_session` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `ethnic_groups` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `evaluations` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `evaluation_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `events` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `event_task` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `event_task_instances` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `forms` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `genders` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `immigration_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `job_titles` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `languages` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `laws` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `law_categories` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `learning_material_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `link_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `maritalstatuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `modules` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_assessments` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_assessment_questions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_assessment_responses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_assessment_response_details` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_questions` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_question_choices` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `module_question_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `notification_groups` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `notification_recurrences` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `organisation_charts` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `policies` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `policy_categories` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `policy_documents` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `products` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `product_categories` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `product_team` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `qualifications` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `report_templates` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `rewards` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `sham_users` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `sham_user_profiles` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `skills` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `surveys` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `survey_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `system_modules` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `system_sub_modules` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `tasks` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `tax_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `teams` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `telephone_numbers` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `thread_statuses` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `timeline_event_types` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `time_groups` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `time_periods` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `titles` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `topics` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `training_delivery_methods` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `users` SET `deleted_at`= now() WHERE `is_active` = 0;
UPDATE `violations` SET `deleted_at`= now() WHERE `is_active` = 0;

ALTER TABLE `addresses` DROP `is_active`;
ALTER TABLE `announcements` DROP `is_active`;
ALTER TABLE `announcement_statuses` DROP `is_active`;
ALTER TABLE `assessments` DROP `is_active`;
ALTER TABLE `assessment_categories` DROP `is_active`;
ALTER TABLE `assessment_category_category_question` DROP `is_active`;
ALTER TABLE `assessment_types` DROP `is_active`;
ALTER TABLE `assets` DROP `is_active`;
ALTER TABLE `asset_conditions` DROP `is_active`;
ALTER TABLE `asset_groups` DROP `is_active`;
ALTER TABLE `asset_suppliers` DROP `is_active`;
ALTER TABLE `branches` DROP `is_active`;
ALTER TABLE `category_questions` DROP `is_active`;
ALTER TABLE `category_question_choices` DROP `is_active`;
ALTER TABLE `category_question_types` DROP `is_active`;
ALTER TABLE `commentdetails` DROP `is_active`;
ALTER TABLE `companies` DROP `is_active`;
ALTER TABLE `countries` DROP `is_active`;
ALTER TABLE `courseparticipantstatuses` DROP `is_active`;
ALTER TABLE `courses` DROP `is_active`;
ALTER TABLE `days` DROP `is_active`;
ALTER TABLE `departments` DROP `is_active`;
ALTER TABLE `disciplinary_actions` DROP `is_active`;
ALTER TABLE `disciplinary_decisions` DROP `is_active`;
ALTER TABLE `divisions` DROP `is_active`;
ALTER TABLE `document_categories` DROP `is_active`;
ALTER TABLE `document_types` DROP `is_active`;
ALTER TABLE `email_addresses` DROP `is_active`;
ALTER TABLE `employees` DROP `is_active`;
ALTER TABLE `employee_attachments` DROP `is_active`;
ALTER TABLE `employee_attachment_types` DROP `is_active`;
ALTER TABLE `employee_evaluation` DROP `is_active`;
ALTER TABLE `employee_statuses` DROP `is_active`;
ALTER TABLE `employee_training_session` DROP `is_active`;
ALTER TABLE `ethnic_groups` DROP `is_active`;
ALTER TABLE `evaluations` DROP `is_active`;
ALTER TABLE `evaluation_statuses` DROP `is_active`;
ALTER TABLE `events` DROP `is_active`;
ALTER TABLE `event_task` DROP `is_active`;
ALTER TABLE `event_task_instances` DROP `is_active`;
ALTER TABLE `forms` DROP `is_active`;
ALTER TABLE `genders` DROP `is_active`;
ALTER TABLE `immigration_statuses` DROP `is_active`;
ALTER TABLE `job_titles` DROP `is_active`;
ALTER TABLE `languages` DROP `is_active`;
ALTER TABLE `laws` DROP `is_active`;
ALTER TABLE `law_categories` DROP `is_active`;
ALTER TABLE `learning_material_types` DROP `is_active`;
ALTER TABLE `link_types` DROP `is_active`;
ALTER TABLE `maritalstatuses` DROP `is_active`;
ALTER TABLE `modules` DROP `is_active`;
ALTER TABLE `module_assessments` DROP `is_active`;
ALTER TABLE `module_assessment_questions` DROP `is_active`;
ALTER TABLE `module_assessment_responses` DROP `is_active`;
ALTER TABLE `module_assessment_response_details` DROP `is_active`;
ALTER TABLE `module_questions` DROP `is_active`;
ALTER TABLE `module_question_choices` DROP `is_active`;
ALTER TABLE `module_question_types` DROP `is_active`;
ALTER TABLE `notification_groups` DROP `is_active`;
ALTER TABLE `notification_recurrences` DROP `is_active`;
ALTER TABLE `organisation_charts` DROP `is_active`;
ALTER TABLE `policies` DROP `is_active`;
ALTER TABLE `policy_categories` DROP `is_active`;
ALTER TABLE `policy_documents` DROP `is_active`;
ALTER TABLE `products` DROP `is_active`;
ALTER TABLE `product_categories` DROP `is_active`;
ALTER TABLE `product_team` DROP `is_active`;
ALTER TABLE `qualifications` DROP `is_active`;
ALTER TABLE `report_templates` DROP `is_active`;
ALTER TABLE `rewards` DROP `is_active`;
ALTER TABLE `sham_users` DROP `is_active`;
ALTER TABLE `sham_user_profiles` DROP `is_active`;
ALTER TABLE `skills` DROP `is_active`;
ALTER TABLE `surveys` DROP `is_active`;
ALTER TABLE `survey_statuses` DROP `is_active`;
ALTER TABLE `system_modules` DROP `is_active`;
ALTER TABLE `system_sub_modules` DROP `is_active`;
ALTER TABLE `tasks` DROP `is_active`;
ALTER TABLE `tax_statuses` DROP `is_active`;
ALTER TABLE `teams` DROP `is_active`;
ALTER TABLE `telephone_numbers` DROP `is_active`;
ALTER TABLE `thread_statuses` DROP `is_active`;
ALTER TABLE `timeline_event_types` DROP `is_active`;
ALTER TABLE `time_groups` DROP `is_active`;
ALTER TABLE `time_periods` DROP `is_active`;
ALTER TABLE `titles` DROP `is_active`;
ALTER TABLE `topics` DROP `is_active`;
ALTER TABLE `training_delivery_methods` DROP `is_active`;
ALTER TABLE `users` DROP `is_active`;
ALTER TABLE `violations` DROP `is_active`;