INSERT INTO job_titles (`job_title_code`, `description`) VALUES
('CCM','CALL CENTRE MANAGER'),
('CSDMUL','CSD MULTICHOICE'),
('DCA','DEBT COLLECTIONS AGENT'),
('DOA','DEBIT ORDER AGENT'),
('INBA','INBOUND AGENT'),
('JM','JUNIOR MANAGER'),
('OPSEXE','OPERATIONS EXECUTIVE'),
('OTRSA','OTRS AGENT'),
('QA ASS','QA ASSESSOR'),
('QA MAN','QA MANAGER'),
('SMSCHA','SMS CHAT'),
('SQLA','SQL AGENT'),
('TL','TEAM LEADER'),
('TRACEA','TRACING AGENT');

INSERT INTO departments (`department_code`, `description`) VALUES
('AFBC','AFRICAN BANK CHARGE OFF'),
('AFBO','AFRICAN BANK ONLINE'),
('CAPF','CAPFIN'),
('CAPI','CAPITEC'),
('CCM','CALL CENTRE MANAGER'),
('COJ','CITY OF JOHANNESBURG'),
('CSD','CLIENT SERVICES'),
('CURO','CURRO'),
('DRAX','DIRECT AXIS'),
('E18%','EDCON 18%'),
('E30%','EDCON 30 - 35%'),
('E805','EDCON 805'),
('E807','EDCON 807'),
('E810','EDCON 810'),
('EDCO','EDCON CHARGE OFF'),
('EDCU','EDCON CURRENT'),
('EDLS','EDCON LATE STAGE'),
('EKHU','EKHURULENI'),
('ESKO','ESKOM'),
('FINC','FINCHOICE'),
('HOME','HOMECHOICE'),
('HOMS','HOMECHOICE SILENT'),
('IDEN','IDENTITY'),
('INBO','INBOUND'),
('JDGR','JD GROUP'),
('JM','JUNIOR MANAGER'),
('MICR','MICRO-LENDING'),
('MORK','MORKALIO'),
('MTN1','MTN STAGE 1'),
('MULT','MULTICHOICE'),
('NEDB','NEDBANK'),
('NFSA','NFSAS'),
('OPSE','OPERATIONS EXECUTIVE'),
('PUBL','PUBLIC SECTOR'),
('QA','QUALITY ASSURANCE'),
('RCS','RCS'),
('RETA','RETAIL'),
('SABC','SABC'),
('SARS','SARS'),
('SQL','SQL'),
('TELK','TELKOM SUSPENSION'),
('TELR','TELERETAIL'),
('TELS','TELKOM STANDARD'),
('TENA','TENACITY'),
('TL','TEAM LEADER'),
('TRAC','TRACING'),
('TRC1','TRUWORTHS CO 1ST PLACEMENT'),
('TRC2','TRUWORTHS CO 2ND PLACEMENT'),
('TRLS','TRUWORTHS LATE STAGE'),
('TRON','TRUWORTHS ONLINE'),
('TRUW','C'),
('TRWH','TRUWORTHS'),
('VIR','VIRGIN ACTIVE'),
('VOD1','VODACOM 1ST PLACEMENT'),
('WESB','WESBANK'),
('WESJ','WESBANK JUDGEMENT'),
('WONG','WONGA');

INSERT INTO titles (`title_code`,`description`) VALUES
('MR','MR'),
('MISS','MISS'),
('MS','MS'),
('MRS','MRS');

INSERT INTO genders (`gender_code`,`description`) VALUES
('M','M'),
('F','F');

INSERT INTO ethnic_groups (`ethnic_group_code`,`description`) VALUES
('A','African'),
('C','Coloured'),
('W','White'),
('I','Indian'),
('O','Other');

INSERT INTO maritalstatuses (`marital_status_code`,`description`) VALUES
('Married','Married'),
('Single','Single'),
('Divorced','Divorced'),
('Widowed','Widowed'),
('Permanently seperated','Permanently seperated');

INSERT INTO tax_statuses (`tax_status_code`,`description`) VALUES
('N.Statutory Tables','Statutory Tables'),
('D.Directive %','Directive %'),
('T.Temporary / Part Time','Temporary / Part Time'),
('P.PAYE Only','PAYE Only'),
('H.PSP – Company','PSP – Company'),
('I.Indep. Contractor','Indep. Contractor'),
('K.PSP – Trust','PSP – Trust'),
('V.No Tax (Director)','No Tax (Director)'),
('W.PAYE (Director)','PAYE (Director)'),
('E.Temporary (Director)','Temporary (Director)'),
('C.Directive (Director','Directive (Director'),
('i.Labour Broker – IRP30','Labour Broker – IRP30'),
('l.Labour Broker – no IRP30','Labour Broker – no IRP30'),
('B.Bread Winner','Bread Winner'),
('R.Resident Tax','Resident Tax'),
('S.Non-Resident Tax','Non-Resident Tax'),
('F.Married','Married'),
('A.Unmarried','Unmarried'),
('x.Secondary / Temp','Secondary / Temp'),
('z.Expat / Non-Resident','Expat / Non-Resident'),
('X.Tax Table (Method Only)','Tax Table (Method Only)'),
('X.No Tax','No Tax'),
('e.ResNonExecDirector','ResNonExecDirector'),
('o.NonResNonExecDir(PAYE)','NonResNonExecDir(PAYE)'),
('v.NonResNonExecDir(Dirt%)','NonResNonExecDir(Dirt%)'),
('m.NonResNonExecDir(Temp)','NonResNonExecDir(Temp)'),
('P.Primary Resident','Primary Resident'),
('R.Primary Non-Resident','Primary Non-Resident'),
('S.Secondary Resident','Secondary Resident'),
('O.Secondary Non-Resident','Secondary Non-Resident'),
('t.Temporary Resident','Temporary Resident'),
('r.Temp Non-Resident','Temp Non-Resident'),
('p.Part-Time Resident','Part-Time Resident'),
('a.Part Time Non-Resident','Part Time Non-Resident'),
('c.Casual Resident','Casual Resident'),
('d.Casual Non-Resident','Casual Non-Resident'),
('f.Full Time Non-Resident','Full Time Non-Resident');

INSERT INTO countries (`country_code`,`description`) VALUES
('AFG','Afghanistan'),
('ALA','Aland Islands'),
('ALB','Albania'),
('DZA','Algeria'),
('ASM','American Samoa'),
('AND','Andorra'),
('AGO','Angola'),
('AIA','Anguilla'),
('ATA','Antarctica'),
('ATG','Antigua and Barbuda'),
('ARG','Argentina'),
('ARM','Armenia'),
('ABW','Aruba'),
('AUS','Australia'),
('AUT','Austria'),
('AZE','Azerbaijan'),
('BHS','Bahamas'),
('BHR','Bahrain'),
('BGD','Bangladesh'),
('BRB','Barbados'),
('BLR','Belarus'),
('BEL','Belgium'),
('BLZ','Belize'),
('BEN','Benin'),
('BMU','Bermuda'),
('BTN','Bhutan'),
('BOL','Bolivia'),
('BIH','Bosnia and Herzegovina'),
('BWA','Botswana'),
('BVT','Bouvet Island'),
('BRA','Brazil'),
('VGB','British Virgin Islands'),
('IOT','British Indian Ocean Territory'),
('BRN','Brunei Darussalam'),
('BGR','Bulgaria'),
('BFA','Burkina Faso'),
('BDI','Burundi'),
('KHM','Cambodia'),
('CMR','Cameroon'),
('CAN','Canada'),
('CPV','Cape Verde'),
('CYM','Cayman Islands'),
('CAF','Central African Republic'),
('TCD','Chad'),
('CHL','Chile'),
('CHN','China'),
('HKG','Hong Kong, SAR China'),
('MAC','Macao, SAR China'),
('CXR','Christmas Island'),
('CCK','Cocos (Keeling) Islands'),
('COL','Colombia'),
('COM','Comoros'),
('COG','Congo (Brazzaville)'),
('COD','Congo, (Kinshasa)'),
('COK','Cook Islands'),
('CRI','Costa Rica'),
('CIV','Côte d\'Ivoire'),
('HRV','Croatia'),
('CUB','Cuba'),
('CYP','Cyprus'),
('CZE','Czech Republic'),
('DNK','Denmark'),
('DJI','Djibouti'),
('DMA','Dominica'),
('DOM','Dominican Republic'),
('ECU','Ecuador'),
('EGY','Egypt'),
('SLV','El Salvador'),
('GNQ','Equatorial Guinea'),
('ERI','Eritrea'),
('EST','Estonia'),
('ETH','Ethiopia'),
('FLK','Falkland Islands (Malvinas)'),
('FRO','Faroe Islands'),
('FJI','Fiji'),
('FIN','Finland'),
('FRA','France'),
('GUF','French Guiana'),
('PYF','French Polynesia'),
('ATF','French Southern Territories'),
('GAB','Gabon'),
('GMB','Gambia'),
('GEO','Georgia'),
('DEU','Germany'),
('GHA','Ghana'),
('GIB','Gibraltar'),
('GRC','Greece'),
('GRL','Greenland'),
('GRD','Grenada'),
('GLP','Guadeloupe'),
('GUM','Guam'),
('GTM','Guatemala'),
('GGY','Guernsey'),
('GIN','Guinea'),
('GNB','Guinea-Bissau'),
('GUY','Guyana'),
('HTI','Haiti'),
('HMD','Heard and Mcdonald Islands'),
('VAT','Holy See (Vatican City State)'),
('HND','Honduras'),
('HUN','Hungary'),
('ISL','Iceland'),
('IND','India'),
('IDN','Indonesia'),
('IRN','Iran, Islamic Republic of'),
('IRQ','Iraq'),
('IRL','Ireland'),
('IMN','Isle of Man'),
('ISR','Israel'),
('ITA','Italy'),
('JAM','Jamaica'),
('JPN','Japan'),
('JEY','Jersey'),
('JOR','Jordan'),
('KAZ','Kazakhstan'),
('KEN','Kenya'),
('KIR','Kiribati'),
('PRK','Korea (North)'),
('KOR','Korea (South)'),
('KWT','Kuwait'),
('KGZ','Kyrgyzstan'),
('LAO','Lao PDR'),
('LVA','Latvia'),
('LBN','Lebanon'),
('LSO','Lesotho'),
('LBR','Liberia'),
('LBY','Libya'),
('LIE','Liechtenstein'),
('LTU','Lithuania'),
('LUX','Luxembourg'),
('MKD','Macedonia, Republic of'),
('MDG','Madagascar'),
('MWI','Malawi'),
('MYS','Malaysia'),
('MDV','Maldives'),
('MLI','Mali'),
('MLT','Malta'),
('MHL','Marshall Islands'),
('MTQ','Martinique'),
('MRT','Mauritania'),
('MUS','Mauritius'),
('MYT','Mayotte'),
('MEX','Mexico'),
('FSM','Micronesia, Federated States of'),
('MDA','Moldova'),
('MCO','Monaco'),
('MNG','Mongolia'),
('MNE','Montenegro'),
('MSR','Montserrat'),
('MAR','Morocco'),
('MOZ','Mozambique'),
('MMR','Myanmar'),
('NAM','Namibia'),
('NRU','Nauru'),
('NPL','Nepal'),
('NLD','Netherlands'),
('ANT','Netherlands Antilles'),
('NCL','New Caledonia'),
('NZL','New Zealand'),
('NIC','Nicaragua'),
('NER','Niger'),
('NGA','Nigeria'),
('NIU','Niue'),
('NFK','Norfolk Island'),
('MNP','Northern Mariana Islands'),
('NOR','Norway'),
('OMN','Oman'),
('PAK','Pakistan'),
('PLW','Palau'),
('PSE','Palestinian Territory'),
('PAN','Panama'),
('PNG','Papua New Guinea'),
('PRY','Paraguay'),
('PER','Peru'),
('PHL','Philippines'),
('PCN','Pitcairn'),
('POL','Poland'),
('PRT','Portugal'),
('PRI','Puerto Rico'),
('QAT','Qatar'),
('REU','Réunion'),
('ROU','Romania'),
('RUS','Russian Federation'),
('RWA','Rwanda'),
('BLM','Saint-Barthélemy'),
('SHN','Saint Helena'),
('KNA','Saint Kitts and Nevis'),
('LCA','Saint Lucia'),
('MAF','Saint-Martin (French part)'),
('SPM','Saint Pierre and Miquelon'),
('VCT','Saint Vincent and Grenadines'),
('WSM','Samoa'),
('SMR','San Marino'),
('STP','Sao Tome and Principe'),
('SAU','Saudi Arabia'),
('SEN','Senegal'),
('SRB','Serbia'),
('SYC','Seychelles'),
('SLE','Sierra Leone'),
('SGP','Singapore'),
('SVK','Slovakia'),
('SVN','Slovenia'),
('SLB','Solomon Islands'),
('SOM','Somalia'),
('ZAF','South Africa'),
('SGS','South Georgia and the South Sandwich Islands'),
('SSD','South Sudan'),
('ESP','Spain'),
('LKA','Sri Lanka'),
('SDN','Sudan'),
('SUR','Suriname'),
('SJM','Svalbard and Jan Mayen Islands'),
('SWZ','Swaziland'),
('SWE','Sweden'),
('CHE','Switzerland'),
('SYR','Syrian Arab Republic (Syria)'),
('TWN','Taiwan, Republic of China'),
('TJK','Tajikistan'),
('TZA','Tanzania, United Republic of'),
('THA','Thailand'),
('TLS','Timor-Leste'),
('TGO','Togo'),
('TKL','Tokelau'),
('TON','Tonga'),
('TTO','Trinidad and Tobago'),
('TUN','Tunisia'),
('TUR','Turkey'),
('TKM','Turkmenistan'),
('TCA','Turks and Caicos Islands'),
('TUV','Tuvalu'),
('UGA','Uganda'),
('UKR','Ukraine'),
('ARE','United Arab Emirates'),
('GBR','United Kingdom'),
('USA','United States of America'),
('UMI','US Minor Outlying Islands'),
('URY','Uruguay'),
('UZB','Uzbekistan'),
('VUT','Vanuatu'),
('VEN','Venezuela (Bolivarian Republic)'),
('VNM','Viet Nam'),
('VIR','Virgin Islands, US'),
('WLF','Wallis and Futuna Islands'),
('ESH','Western Sahara'),
('YEM','Yemen'),
('ZMB','Zambia'),
('ZWE','Zimbabwe');
