INSERT INTO job_titles (`job_title_code`, `description`) VALUES
('CCM','CALL CENTRE MANAGER'),
('CSDMUL','CSD MULTICHOICE'),
('DCA','DEBT COLLECTIONS AGENT'),
('DOA','DEBIT ORDER AGENT'),
('INBA','INBOUND AGENT'),
('JM','JUNIOR MANAGER'),
('OPSEXE','OPERATIONS EXECUTIVE'),
('OTRSA','OTRS AGENT'),
('QA ASS','QA ASSESSOR'),
('QA MAN','QA MANAGER'),
('SMSCHA','SMS CHAT'),
('SQLA','SQL AGENT'),
('TL','TEAM LEADER'),
('TRACEA','TRACING AGENT');

INSERT INTO departments (`department_code`, `description`) VALUES
('AFBC','AFRICAN BANK CHARGE OFF'),
('AFBO','AFRICAN BANK ONLINE'),
('CAPF','CAPFIN'),
('CAPI','CAPITEC'),
('CCM','CALL CENTRE MANAGER'),
('COJ','CITY OF JOHANNESBURG'),
('CSD','CLIENT SERVICES'),
('CURO','CURRO'),
('DRAX','DIRECT AXIS'),
('E18%','EDCON 18%'),
('E30%','EDCON 30 - 35%'),
('E805','EDCON 805'),
('E807','EDCON 807'),
('E810','EDCON 810'),
('EDCO','EDCON CHARGE OFF'),
('EDCU','EDCON CURRENT'),
('EDLS','EDCON LATE STAGE'),
('EKHU','EKHURULENI'),
('ESKO','ESKOM'),
('FINC','FINCHOICE'),
('HOME','HOMECHOICE'),
('HOMS','HOMECHOICE SILENT'),
('IDEN','IDENTITY'),
('INBO','INBOUND'),
('JDGR','JD GROUP'),
('JM','JUNIOR MANAGER'),
('MICR','MICRO-LENDING'),
('MORK','MORKALIO'),
('MTN1','MTN STAGE 1'),
('MULT','MULTICHOICE'),
('NEDB','NEDBANK'),
('NFSA','NFSAS'),
('OPSE','OPERATIONS EXECUTIVE'),
('PUBL','PUBLIC SECTOR'),
('QA','QUALITY ASSURANCE'),
('RCS','RCS'),
('RETA','RETAIL'),
('SABC','SABC'),
('SARS','SARS'),
('SQL','SQL'),
('TELK','TELKOM SUSPENSION'),
('TELR','TELERETAIL'),
('TELS','TELKOM STANDARD'),
('TENA','TENACITY'),
('TL','TEAM LEADER'),
('TRAC','TRACING'),
('TRC1','TRUWORTHS CO 1ST PLACEMENT'),
('TRC2','TRUWORTHS CO 2ND PLACEMENT'),
('TRLS','TRUWORTHS LATE STAGE'),
('TRON','TRUWORTHS ONLINE'),
('TRUW','C'),
('TRWH','TRUWORTHS'),
('VIR','VIRGIN ACTIVE'),
('VOD1','VODACOM 1ST PLACEMENT'),
('WESB','WESBANK'),
('WESJ','WESBANK JUDGEMENT'),
('WONG','WONGA');

INSERT INTO titles (`title_code`,`description`) VALUES
('MR','MR'),
('MISS','MISS'),
('MS','MS'),
('MRS','MRS');

INSERT INTO genders (`gender_code`,`description`) VALUES
('M','M'),
('F','F');

INSERT INTO ethnic_groups (`ethnic_group_code`,`description`) VALUES
('A','African'),
('C','Coloured'),
('W','White'),
('I','Indian'),
('O','Other');

INSERT INTO maritalstatuses (`marital_status_code`,`description`) VALUES
('Married','Married'),
('Single','Single'),
('Divorced','Divorced'),
('Widowed','Widowed'),
('Permanently seperated','Permanently seperated');

INSERT INTO tax_statuses (`tax_status_code`,`description`) VALUES
('N.Statutory Tables','Statutory Tables'),
('D.Directive %','Directive %'),
('T.Temporary / Part Time','Temporary / Part Time'),
('P.PAYE Only','PAYE Only'),
('H.PSP – Company','PSP – Company'),
('I.Indep. Contractor','Indep. Contractor'),
('K.PSP – Trust','PSP – Trust'),
('V.No Tax (Director)','No Tax (Director)'),
('W.PAYE (Director)','PAYE (Director)'),
('E.Temporary (Director)','Temporary (Director)'),
('C.Directive (Director','Directive (Director'),
('i.Labour Broker – IRP30','Labour Broker – IRP30'),
('l.Labour Broker – no IRP30','Labour Broker – no IRP30'),
('B.Bread Winner','Bread Winner'),
('R.Resident Tax','Resident Tax'),
('S.Non-Resident Tax','Non-Resident Tax'),
('F.Married','Married'),
('A.Unmarried','Unmarried'),
('x.Secondary / Temp','Secondary / Temp'),
('z.Expat / Non-Resident','Expat / Non-Resident'),
('X.Tax Table (Method Only)','Tax Table (Method Only)'),
('X.No Tax','No Tax'),
('e.ResNonExecDirector','ResNonExecDirector'),
('o.NonResNonExecDir(PAYE)','NonResNonExecDir(PAYE)'),
('v.NonResNonExecDir(Dirt%)','NonResNonExecDir(Dirt%)'),
('m.NonResNonExecDir(Temp)','NonResNonExecDir(Temp)'),
('P.Primary Resident','Primary Resident'),
('R.Primary Non-Resident','Primary Non-Resident'),
('S.Secondary Resident','Secondary Resident'),
('O.Secondary Non-Resident','Secondary Non-Resident'),
('t.Temporary Resident','Temporary Resident'),
('r.Temp Non-Resident','Temp Non-Resident'),
('p.Part-Time Resident','Part-Time Resident'),
('a.Part Time Non-Resident','Part Time Non-Resident'),
('c.Casual Resident','Casual Resident'),
('d.Casual Non-Resident','Casual Non-Resident'),
('f.Full Time Non-Resident','Full Time Non-Resident');
